import Head from 'next/head';
import Card from './components/card';

export default function Home() {
 return (
    <div className='bg'>
      <Head>
        <title>Audit Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <section>
         <h1>Post Update</h1>
        <div className='content'>  
          <div className="input-bar">
            <input type="text" placeholder="What's happening?"/>
            <button>Tweet</button>
          </div>

          <Card/>
        </div>

        </section>

    </div>
  )
}
