import Head from 'next/head';
import Prism from '../prism';
import Card from './components/card';

export default function Home() {
 return (
    <div className='isolate'>
      <div className='noise'>
      <div className='overlay'>
      <Head>
        <title>Audit Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
     
      <h1>Post Update</h1>
      <div className='content'>
        <Card/>
      </div>
      </div>
      </div>
    </div>
  )
}
