import Head from 'next/head'


export default function Home() {
  return (
    <>
      <Head>
        <title>under construction </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Under Construct 🚧</h1>
      <p>BRUH</p>
      <pre>
        this code has been refactor :default
      </pre>
    </>
  )
}
